global:
  scrape_interval: 10s # Cào dữ liệu mỗi 10 giây
  evaluation_interval: 10s

scrape_configs:
  # Job 1: Giám sát chính bản thân Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job 2: Giám sát Spring Boot Backend
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus' # Đường dẫn Actuator mở ra
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8080'] # 'backend' là tên service trong docker-compose